### ISSUE TITLE
Impossible to build docker container with Hack solution

### ISSUE THREAD

**Issue by obigroup** [cozy/cozy-home#322]
Bonjour,

J'ai essayé de contruire mon containeur docker avec la solution de Hack comme indiqué dans votre README, cela ne fonctionne pas...

Voici mon fichier dockerfile:
########
FROM dockerfile/nodejs

RUN git clone https://github.com/cozy/cozy-home /usr/cozy/home
RUN cd /usr/cozy/home; npm install --production

EXPOSE 9103
CMD cd /usr/cozy/home/; HOST=0.0.0.0 DATASYSTEM_HOST=$DATASYSTEM_PORT_9101_TCP_ADDR DATASYSTEM_PORT=$DATASYSTEM_PORT_9101_TCP_PORT npm start

########

Voici les erreurs lors du build :

```
npm WARN package.json cozy-home@1.0.39 No repository field.

> bcrypt@0.7.7 install /usr/cozy/home/node_modules/bcrypt
> node-gyp rebuild

make: Entering directory `/usr/cozy/home/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
../src/bcrypt_node.cc: In destructor 'virtual {anonymous}::baton_base::~baton_base()':
../src/bcrypt_node.cc:118:18: error: 'class v8::Persistent<v8::Function>' has no member named 'Dispose'
         callback.Dispose();
                  ^
../src/bcrypt_node.cc: At global scope:
../src/bcrypt_node.cc:202:19: error: variable or field 'GenSaltAsync' declared void
 void GenSaltAsync(uv_work_t* req) {
                   ^
../src/bcrypt_node.cc:202:19: error: 'uv_work_t' was not declared in this scope
../src/bcrypt_node.cc:202:30: error: 'req' was not declared in this scope
 void GenSaltAsync(uv_work_t* req) {
                              ^
../src/bcrypt_node.cc:487:30: error: expected '}' at end of input
 NODE_MODULE(bcrypt_lib, init);
                              ^
../src/bcrypt_node.cc:85:13: warning: 'void crypto_lock_init()' defined but not used [-Wunused-function]
 static void crypto_lock_init(void) {
             ^
../src/bcrypt_node.cc:95:13: warning: 'void crypto_lock_cb(int, int, const char*, int)' defined but not used [-Wunused-function]
 static void crypto_lock_cb(int mode, int n, const char* file, int line) {
             ^
../src/bcrypt_node.cc:105:22: warning: 'long unsigned int crypto_id_cb()' defined but not used [-Wunused-function]
 static unsigned long crypto_id_cb(void) {
                      ^
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
make: Leaving directory `/usr/cozy/home/node_modules/bcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/cozy/home/node_modules/bcrypt
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 

> ws@0.5.0 install /usr/cozy/home/node_modules/cozy-realtime-adapter/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/usr/cozy/home/node_modules/cozy-realtime-adapter/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/usr/cozy/home/node_modules/cozy-realtime-adapter/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'

> ws@0.4.31 install /usr/cozy/home/node_modules/cozy-realtime-adapter/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/usr/cozy/home/node_modules/cozy-realtime-adapter/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: Leaving directory `/usr/cozy/home/node_modules/cozy-realtime-adapter/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--production"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.3
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.7.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.7.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/cozy/home/npm-debug.log
Service 'home' failed to build: The command [/bin/sh -c cd /usr/cozy/home; npm install --production] returned a non-zero code: 1
```
Une idée de comment résoudre le problème ?

Merci,
Rony.

**Comment by frankrousseau** [comment]
Bonjour,
 Je ne comprends pas bien ce que vous essayez de faire. Pouvez vous nous dire à quel README vous faites référence ?

Pour installer Cozy dans un Docker, nous vous conseillons plutôt le tutoriel suivant : 
https://github.com/cozy-labs/cozy-docker

**Comment by obigroup** [comment]
Bonjour,

J'ai essayé d'installer l'intégralité de cozy sous forme de containeurs docker.
Je me suis inspiré de https://github.com/mycozycloud/labs-controller mais rien à faire, les modules cozy sont trop liés les uns aux autres.

J'ai donc préféré séparer les modules qui ne sont pas sous nodejs : DataIndexer et CouchDB.
J'ai commencé la modification des autres modules à cette adresse : https://github.com/obigroup pour qu'ils puissent accéder à un Indexer et un Couchdb distants.

Merci.
Ps: le ticket peut être fermé.

**Comment by obigroup** [comment]
Bonjour,

Je reviens sur le ticket, quand je lance l'installation du module avec la méthode indiquée dans votre doc je me retrouve avec une erreur: 

Manip1 :
git clone https://github.com/mycozycloud/cozy-home.git
npm install --production

Erreur:
```
make: Entering directory `/usr/cozy/cozy-home/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
../src/bcrypt_node.cc: In destructor 'virtual {anonymous}::baton_base::~baton_base()':
../src/bcrypt_node.cc:118:18: error: 'class v8::Persistent<v8::Function>' has no member named 'Dispose'
         callback.Dispose();
                  ^
../src/bcrypt_node.cc: At global scope:
../src/bcrypt_node.cc:202:19: error: variable or field 'GenSaltAsync' declared void
 void GenSaltAsync(uv_work_t* req) {
                   ^
../src/bcrypt_node.cc:202:19: error: 'uv_work_t' was not declared in this scope
../src/bcrypt_node.cc:202:30: error: 'req' was not declared in this scope
 void GenSaltAsync(uv_work_t* req) {
                              ^
../src/bcrypt_node.cc:487:30: error: expected '}' at end of input
 NODE_MODULE(bcrypt_lib, init);
                              ^
../src/bcrypt_node.cc:85:13: warning: 'void crypto_lock_init()' defined but not used [-Wunused-function]
 static void crypto_lock_init(void) {
             ^
../src/bcrypt_node.cc:95:13: warning: 'void crypto_lock_cb(int, int, const char*, int)' defined but not used [-Wunused-function]
 static void crypto_lock_cb(int mode, int n, const char* file, int line) {
             ^
../src/bcrypt_node.cc:105:22: warning: 'long unsigned int crypto_id_cb()' defined but not used [-Wunused-function]
 static unsigned long crypto_id_cb(void) {
                      ^
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
make: Leaving directory `/usr/cozy/cozy-home/node_modules/bcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/cozy/cozy-home/node_modules/bcrypt
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
 
> ws@0.5.0 install /usr/cozy/cozy-home/node_modules/cozy-realtime-adapter/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/usr/cozy/cozy-home/node_modules/cozy-realtime-adapter/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/usr/cozy/cozy-home/node_modules/cozy-realtime-adapter/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
 
> ws@0.4.31 install /usr/cozy/cozy-home/node_modules/cozy-realtime-adapter/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/usr/cozy/cozy-home/node_modules/cozy-realtime-adapter/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: Leaving directory `/usr/cozy/cozy-home/node_modules/cozy-realtime-adapter/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--production"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.3
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.7.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.7.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/cozy/cozy-home/npm-debug.log
```

Manip2:
/usr/cozy/cozy-monitor/bin/cozy-monitor install home

Erreur: 
info - Install started for home...
error - An error occured:
error - Install failed for home.
[Error: Error: Parsing error : Unexpected token B, body= 
 Bad Request]

**Comment by aenario** [comment]
Cozy n'est pour le moment pas compatible avec node 0.12, il faut downgrade à 0.10.

**Comment by clochix** [comment]
@obigroup le problème de compatibilité avec Node 0.12 pourrait être corrigé par 600d77c. Une fois qu'il aura été publié, tu pourras re-tester (si tu es toujours là dessus ;-) )

**Comment by frankrousseau** [comment]
Cozy est désormais compatible avec Node 4. @obigroup peux-tu retester ?

**Comment by poupotte** [comment]
Le problème est résolu avec Node 4. De plus, Cozy ne supporte pas officiellement Docker.
