### ISSUE TITLE
Impossible d'installer le module avec la Hack méthode

### ISSUE THREAD

**Issue by obigroup** [cozy/cozy-home#328]
Bonjour,

Je reviens sur le ticket #322, quand je lance l'installation du module avec la méthode indiquée dans votre doc je me retrouve avec une erreur: 

Manip1 :
git clone https://github.com/mycozycloud/cozy-home.git
npm install --production

Erreur:
```
make: Entering directory `/usr/cozy/cozy-home/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
../src/bcrypt_node.cc: In destructor 'virtual {anonymous}::baton_base::~baton_base()':
../src/bcrypt_node.cc:118:18: error: 'class v8::Persistent<v8::Function>' has no member named 'Dispose'
         callback.Dispose();
                  ^
../src/bcrypt_node.cc: At global scope:
../src/bcrypt_node.cc:202:19: error: variable or field 'GenSaltAsync' declared void
 void GenSaltAsync(uv_work_t* req) {
                   ^
../src/bcrypt_node.cc:202:19: error: 'uv_work_t' was not declared in this scope
../src/bcrypt_node.cc:202:30: error: 'req' was not declared in this scope
 void GenSaltAsync(uv_work_t* req) {
                              ^
../src/bcrypt_node.cc:487:30: error: expected '}' at end of input
 NODE_MODULE(bcrypt_lib, init);
                              ^
../src/bcrypt_node.cc:85:13: warning: 'void crypto_lock_init()' defined but not used [-Wunused-function]
 static void crypto_lock_init(void) {
             ^
../src/bcrypt_node.cc:95:13: warning: 'void crypto_lock_cb(int, int, const char*, int)' defined but not used [-Wunused-function]
 static void crypto_lock_cb(int mode, int n, const char* file, int line) {
             ^
../src/bcrypt_node.cc:105:22: warning: 'long unsigned int crypto_id_cb()' defined but not used [-Wunused-function]
 static unsigned long crypto_id_cb(void) {
                      ^
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
make: Leaving directory `/usr/cozy/cozy-home/node_modules/bcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/cozy/cozy-home/node_modules/bcrypt
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
 
> ws@0.5.0 install /usr/cozy/cozy-home/node_modules/cozy-realtime-adapter/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/usr/cozy/cozy-home/node_modules/cozy-realtime-adapter/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/usr/cozy/cozy-home/node_modules/cozy-realtime-adapter/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
 
> ws@0.4.31 install /usr/cozy/cozy-home/node_modules/cozy-realtime-adapter/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/usr/cozy/cozy-home/node_modules/cozy-realtime-adapter/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: Leaving directory `/usr/cozy/cozy-home/node_modules/cozy-realtime-adapter/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--production"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.3
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.7.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.7.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/cozy/cozy-home/npm-debug.log
```

Manip2:
/usr/cozy/cozy-monitor/bin/cozy-monitor install home

Erreur: 
info - Install started for home...
error - An error occured:
error - Install failed for home.
[Error: Error: Parsing error : Unexpected token B, body= 
 Bad Request]

**Comment by frankrousseau** [comment]
On dirait que c'est la dépendance bcrypt qui pose problème. Elle ne trouve pas les bons outils pour être compilée.

**Comment by obigroup** [comment]
Oui il semblerait que cela provienne de ma version de node.
Je suis passé sous la version 0.10.x et cela marche.

Merci.

**Comment by frankrousseau** [comment]
Ok effectivement il va falloir qu'on s'attaque au passage à Node 0.12.

**Comment by frankrousseau** [comment]
Peux-t-on fermer ce ticket ?

**Comment by obigroup** [comment]
Oui pas de soucis, j'ai encore d'autres problèmes mais j'ouvrirai des tickets aux bons endroits.

Merci.

**Comment by frankrousseau** [comment]
Ok cool merci. N'hésitez pas à nous parler de votre cas d'utilisation aussi. Ca peut nous aider pour répondre (et nous sommes curieux aussi ;)).
