### ISSUE TITLE
Exception when sending server logs

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-home#554]
```
TypeError: Object /usr/local/cozy/apps/home/build/cozy.tar.gz has no method 'join'
    at Object.module.exports.logs.getCompressLogs (/usr/local/cozy/apps/home/build/server/lib/logs.js:54:17)
    at /usr/local/cozy/apps/home/build/server/controllers/help.js:65:23
    at /usr/local/cozy/apps/home/build/server/models/cozyinstance.js:21:14
    at /usr/local/cozy/apps/home/node_modules/cozydb/lib/model.js:200:18
    at /usr/local/cozy/apps/home/node_modules/cozydb/lib/cozymodel.js:254:18
    at parseBody (/usr/local/cozy/apps/home/node_modules/cozydb/node_modules/request-json-light/main.js:75:10)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/home/node_modules/cozydb/node_modules/request-json-light/main.js:109:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
```

**Comment by poupotte** [comment]
Thanks @clochix :)
