### ISSUE TITLE
Revocation of device led to full cozy crash

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-home#561]
Hi,

I tried to delete a device from "state" panels (the device was created from cozy-desktop).
Proxy log:
```
[Tue, 03 Nov 2015 10:45:36 GMT] - DELETE /api/devices/980dc94aac3997be122a18d58a000582 - 500 - 18.116 ms -  21
 ```
Home log: 
```
[Tue, 03 Nov 2015 10:45:36 GMT] - DELETE /api/devices/980dc94aac3997be122a18d58a000582 - 500 - 18.116 ms -  21
```

**Comment by clochix** [comment]
Thanks for reporting @ZeHiro.
Don't you have more logs ? The errors of the Home application are now logged into an home-err.log file if you updated the controller.

**Comment by ZeHiro** [comment]
Here is what I have: 

```
Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
Error: socket hang up
    at createHangUpError (http.js:1472:15)
    at Socket.socketOnEnd [as onend] (http.js:1568:23)
    at Socket.g (events.js:180:16)
    at Socket.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
Error: socket hang up
    at createHangUpError (http.js:1472:15)
    at Socket.socketOnEnd [as onend] (http.js:1568:23)
    at Socket.g (events.js:180:16)
    at Socket.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

**Comment by ZeHiro** [comment]
Seems to be due to a d-s crash (after oom kill). I close
