### ISSUE TITLE
Error when updating platform and applications

### ISSUE THREAD

**Issue by babolivier** [cozy/cozy-home#595]
So today, when I went to the "Status" page, I saw a button "Update plaform and applications" (probably related to the available cozy-term update). However, when I clicked it, the loading animation started rotating in an infinite loop, and when I went to have a look at the Home's logs, I saw this error:

```
[Mon, 16 Nov 2015 07:53:17 GMT] - PUT /api/applications/update/all - 200 - 27460.072 ms -  62
error - home:client | {"type":"error","error":{"msg":"Uncaught TypeError: Cannot convert undefined or null to object","name":"TypeError","full":"TypeError: Cannot convert undefined or null to object","stack":"TypeError: Cannot convert undefined or null to object\n    at presuccess (https://cozy.brendanabolivier.com/javascripts/app.js:4636:20)\n    at Object.callbacks.success (https://cozy.brendanabolivier.com/javascripts/app.js:4643:9)\n    at fire (https://cozy.brendanabolivier.com/javascripts/vendor.js:1171:30)\n    at Object.self.fireWith [as resolveWith] (https://cozy.brendanabolivier.com/javascripts/vendor.js:1289:7)\n    at done (https://cozy.brendanabolivier.com/javascripts/vendor.js:7524:14)\n    at XMLHttpRequest.callback (https://cozy.brendanabolivier.com/javascripts/vendor.js:8305:8)"},"url":"https://cozy.brendanabolivier.com/javascripts/app.js","line":4636,"col":20,"href":"https://cozy.brendanabolivier.com/#config-applications"}
error - home:client | TypeError: Cannot convert undefined or null to object
    at presuccess (https://cozy.brendanabolivier.com/javascripts/app.js:4636:20)
    at Object.callbacks.success (https://cozy.brendanabolivier.com/javascripts/app.js:4643:9)
    at fire (https://cozy.brendanabolivier.com/javascripts/vendor.js:1171:30)
    at Object.self.fireWith [as resolveWith] (https://cozy.brendanabolivier.com/javascripts/vendor.js:1289:7)
    at done (https://cozy.brendanabolivier.com/javascripts/vendor.js:7524:14)
    at XMLHttpRequest.callback (https://cozy.brendanabolivier.com/javascripts/vendor.js:8305:8)
```

**Comment by clochix** [comment]
Thanks for reporting @babolivier 
@nicofrand seems to have a similar stack trace in #594.

**Comment by nono** [comment]
@poupotte I think you fix this error with https://github.com/cozy/cozy-home/commit/5d1e3ba8502ee2d7ee06f5a1a45da4eab7c82e23

**Comment by poupotte** [comment]
This issue is now fixed.
