### ISSUE TITLE
Blank error message after stack update

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-home#677]
Reported by @nicofrand : 
![cozy-bug-maj](https://cloud.githubusercontent.com/assets/384908/13001723/cf233c0a-d168-11e5-94d7-c387b2d3b904.png)

Related to https://github.com/cozy/cozy-home/blob/master/client/app/views/update_stack_modal.coffee#L69

**Comment by nicofrand** [comment]
To complete the issue : that happened after the last controller update and once I clicked on "OK", everythink seemed to be fine, despite the alert.

**Comment by nicofrand** [comment]
Here are some logs from the controller:

```console
[2016-02-12 08:40:35:578] info - lib:controller | kresus:stop application                                                                                                                                                       
[2016-02-12 08:40:35:579] info - server | Process exit with code 0                                                                                                                                                              
                                                                                                                                                                                                                                
node.js:328                                                                                                                                                                                                                     
      if (!x) throw new Error(msg || 'assertion error');                                                                                                                                                                        
                    ^                                                                                                                                                                                                           
Error: assertion error                                                                                                                                                                                                          
    at process.assert (node.js:328:21)                                                                                                                                                                                          
    at process.removeListener (node.js:808:9)                                                                                                                                                                                   
    at /usr/lib/node_modules/cozy-controller/build/server.js:81:17                                                                                                                                                              
    at stopApps (/usr/lib/node_modules/cozy-controller/build/server/lib/controller.js:95:12)                                                                                                                                    
    at Object.module.exports.stopAll (/usr/lib/node_modules/cozy-controller/build/server/lib/controller.js:353:10)                                                                                                              
    at process.exitProcess (/usr/lib/node_modules/cozy-controller/build/server.js:79:25)                                                                                                                                        
    at process.g (events.js:180:16)                                                                                                                                                                                             
    at process.emit (events.js:95:17)                                                                                                                                                                                           
    at process.exit (node.js:740:17)                                                                                                                                                                                            
    at /usr/lib/node_modules/cozy-controller/build/server.js:88:24                                                                                                                                                              
[2016-02-12 08:40:40:262] info - init | ### FILE INITIALIZATION ###                                                                                                                                                             
[2016-02-12 08:40:40:319] info - init | init: source directory                                                                                                                                                                  
[2016-02-12 08:40:40:326] info - init | init: stack file                                                                                                                                                                        
[2016-02-12 08:40:40:334] info - init | init: token file                                                                                                                                                                        
[2016-02-12 08:40:40:339] info - lib:autostart | ### AUTOSTART ###                                                                                                                                                              
[2016-02-12 08:40:40:378] info - lib:autostart | couchDB: started   
```
