### ISSUE TITLE
TypeError: Cannot read property 'localeCompare' of undefined

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-home#712]
[Reported in the forum](https://forum.cozy.io/t/platform-update-08-03-2016/2131):
```
TypeError: Cannot read property 'localeCompare' of undefined(…) "TypeError:  Cannot read property 'localeCompare' of undefined
at ApplicationCollection.module.exports.ApplicationCollection.comparator (https://xxxxx.cozycloud.cc/javascripts/app.js:159:42)
at Array.sort (native)
at ApplicationCollection._.extend.sort (https://xxxxx.cozycloud.cc/javascripts/vendor.js:11443:21)
at ApplicationCollection._.extend.set (https://xxxxx.cozycloud.cc/javascripts/vendor.js:11340:22)
at ApplicationCollection._.extend.add (https://xxxxx.cozycloud.cc/javascripts/vendor.js:11255:19)
at ApplicationCollection._.extend.reset (https://xxxxx.cozycloud.cc/javascripts/vendor.js:11365:12)
at ApplicationCollection.Backbone.Collection (https://xxxxx.cozycloud.cc/javascripts/vendor.js:11224:22)
at ApplicationCollection.BaseCollection [as constructor] (https://xxxxx.cozycloud.cc/javascripts/app.js:521:49)
at new ApplicationCollection (https://xxxx.cozycloud.cc/javascripts/app.js:125:56)
at new HomeView (https://xxxxxx.cozycloud.cc/javascripts/app.js:10237:17)
```

Seems releted to 6c620a1
This is e blocking bug, as it prevents the Home application to start. @nono could you have a look at this one please?

**Comment by poupotte** [comment]
This issue should be fixed. Don't hesistate to reopen it if necessary.
