### ISSUE TITLE
TypeError: Cannot call method 'replace' of undefined

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-home#748]
A user get this error trying to install Music application. Looks like its server (hosted on our infrastructure) is having trouble getting the manifest on Github.

```
Error: Parsing error : Unexpected token N, body=
 Not Found
    at parseBody (/usr/local/cozy/apps/home/node_modules/request-json/main.js:19:19)
    at Request._callback (/usr/local/cozy/apps/home/node_modules/request-json/main.js:68:18)
    at Request.self.callback (/usr/local/cozy/apps/home/node_modules/request-json/node_modules/request/index.js:148:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/cozy/apps/home/node_modules/request-json/node_modules/request/index.js:876:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/home/node_modules/request-json/node_modules/request/index.js:827:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
[TypeError: Cannot call method 'replace' of undefined]
TypeError: Cannot call method 'replace' of undefined
    at Manifest.exports.Manifest.Manifest.getMetaData (/usr/local/cozy/apps/home/build/server/lib/manifest.js:137:47)
    at Manifest.getMetaData (/usr/local/cozy/apps/home/build/server/lib/manifest.js:3:57)
    at /usr/local/cozy/apps/home/build/server/controllers/applications.js:248:27
    at /usr/local/cozy/apps/home/build/server/lib/manifest.js:41:22
    at /usr/local/cozy/apps/home/build/server/lib/git_providers.js:37:14
    at parseBody (/usr/local/cozy/apps/home/node_modules/request-json/main.js:26:12)
    at Request._callback (/usr/local/cozy/apps/home/node_modules/request-json/main.js:68:18)
    at Request.self.callback (/usr/local/cozy/apps/home/node_modules/request-json/node_modules/request/index.js:148:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/cozy/apps/home/node_modules/request-json/node_modules/request/index.js:876:14)
```

**Comment by clochix** [comment]
Closing, as the version of Home was pretty old.
